[toolchain]
anchor_version = "0.30.1"
solana_version = "2.0.24"

[test]
startup_wait = 100000

[features]
resolution = true
skip-lint = false

[test.validator]
url = "https://explorer-api.devnet.solana.com/" 

[[test.validator.clone]]
address = "BoNsHRcyLLNdtnoDf8hiCNZpyehMC4FDMxs6NTxFi3ew" #chainlink Sprogram

[programs.localnet]
bonsol_pow_pow = "6C9bFAAkLwHNLCCgaZUQxEsYFPEJPeRUyavhaBe6zXNN"

[provider]
cluster = "Localnet"
#test do not use anywhere
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"
