[toolchain]
anchor_version = "0.30.1"
solana_version = "2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonsol_pow_pow= "6C9bFAAkLwHNLCCgaZUQxEsYFPEJPeRUyavhaBe6zXNN"

[provider]
cluster = "Localnet"
wallet = "testkp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
