[package]
name = "collatz"
version = "0.1.0"
edition = "2021"

[package.metadata.zkprogram]
input_order = ["Private", "Private"]

[build]
target-dir = "./target"

[workspace]

[dependencies]
risc0-zkvm = {version="1.2.1", default-features = false, features = ["std"]}
num-bigint = "0.4.4"